### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by MyZik** [danielpanzella/bitbucket-api-bundle#1]
Hi!

I'm trying to use this library and have some problems with Symfony 4.4...

Error:
```
In OAuth2Listener.php line 79:

  Can't fetch access_token.


In OAuth2Listener.php line 135:

  access_token is missing from response. {"error_description": "Client credentials missing; th
  is request needs to be authenticated with the OAuth client id and secret", "error": "unautho
  rized_client"}
```

My files:
/config/services.yml:
```yml
imports:
    - { resource: 'parameters.yml' }

services:
    ...
```

/config/parameters.yml:
```yml
parameters:
    bitbucket_api:
        client_id: "test"
        client_secret: "testsecret"
```

But the bundle don't see the files...
